import 'character_config.dart';

class CharacterRegistry {
  static const List<CharacterConfig> characters = [
    spineboy,
    chibiStickers,
    mixAndMatch,
    owl,
  ];

  static CharacterConfig getById(String id) {
    return characters.firstWhere(
      (c) => c.id == id,
      orElse: () => chibiStickers,
    );
  }

  static const spineboy = CharacterConfig(
    id: 'spineboy',
    displayName: 'Spineboy',
    atlasAsset: 'assets/spine/spineboy/spineboy-pma.atlas',
    skelAsset: 'assets/spine/spineboy/spineboy-pro.skel',
    supportsLipSync: true,
    oneShotAnimations: {'death', 'jump', 'shoot', 'portal'},
    idleAnimation: 'idle',
    emotionAnimations: {
      'neutral': 'idle',
      'happy': 'hoverboard',
      'angry': 'aim',
      'sad': 'death',
      'surprised': 'jump',
      'annoyed': 'aim',
      'disappointed': 'idle',
      'scolding': 'shoot',
      'proud': 'hoverboard',
      'worried': 'idle',
    },
    gestureAnimations: {
      'idle': 'idle',
      'pointing': 'aim',
      'waving': 'portal',
      'arms_crossed': 'idle',
      'shaking_head': 'walk',
      'crawling_in': 'portal',
      'thumbs_up': 'hoverboard',
      'clapping': 'hoverboard',
      'facepalm': 'death',
      'beckoning': 'walk',
    },
  );

  static const chibiStickers = CharacterConfig(
    id: 'chibi-stickers',
    displayName: 'Chibi',
    atlasAsset: 'assets/spine/chibi-stickers/chibi-stickers-pma.atlas',
    skelAsset: 'assets/spine/chibi-stickers/chibi-stickers.skel',
    supportsLipSync: false,
    defaultSkin: 'misaki',
    oneShotAnimations: {
      'emotes/hooray',
      'emotes/idea',
      'emotes/angry',
      'emotes/crying',
      'emotes/love',
      'emotes/laugh',
      'emotes/dead',
      'emotes/confused',
      'emotes/excited',
      'emotes/flushed',
      'emotes/determined',
      'emotes/dramatic-stare',
      'emotes/fawning',
      'emotes/burp',
      'emotes/just-right',
    },
    idleAnimation: 'emotes/fawning',
    emotionAnimations: {
      'neutral': 'emotes/fawning',
      'happy': 'emotes/hooray',
      'angry': 'emotes/angry',
      'sad': 'emotes/crying',
      'surprised': 'emotes/excited',
      'annoyed': 'emotes/dramatic-stare',
      'disappointed': 'emotes/dead',
      'scolding': 'emotes/angry',
      'proud': 'emotes/just-right',
      'worried': 'emotes/confused',
    },
    gestureAnimations: {
      'idle': 'emotes/fawning',
      'pointing': 'emotes/idea',
      'waving': 'emotes/love',
      'arms_crossed': 'emotes/determined',
      'shaking_head': 'emotes/confused',
      'crawling_in': 'emotes/excited',
      'thumbs_up': 'emotes/hooray',
      'clapping': 'emotes/laugh',
      'facepalm': 'emotes/dead',
      'beckoning': 'emotes/fawning',
    },
  );

  static const mixAndMatch = CharacterConfig(
    id: 'mix-and-match',
    displayName: 'Mix & Match',
    atlasAsset: 'assets/spine/mix-and-match/mix-and-match-pma.atlas',
    skelAsset: 'assets/spine/mix-and-match/mix-and-match-pro.skel',
    supportsLipSync: false,
    supportsDressUp: true,
    baseSkins: ['skin-base'],
    oneShotAnimations: {'dress-up'},
    combineSkins: [
      'skin-base',
      'clothes/dress-blue',
      'eyelids/girly',
      'eyes/eyes-blue',
    ],
    idleAnimation: 'idle',
    emotionAnimations: {
      'neutral': 'idle',
      'happy': 'dance',
      'angry': 'walk',
      'sad': 'idle',
      'surprised': 'dress-up',
      'annoyed': 'aware',
      'disappointed': 'walk',
      'scolding': 'walk',
      'proud': 'dance',
      'worried': 'aware',
    },
    emotionAnimationSpeeds: {
      'neutral': 1.0,
      'happy': 1.0,
      'angry': 1.5,
      'sad': 0.5,
      'surprised': 1.0,
      'annoyed': 0.8,
      'disappointed': 0.6,
      'scolding': 1.3,
      'proud': 0.7,
      'worried': 1.2,
    },
    gestureAnimations: {
      'idle': 'idle',
      'pointing': 'aware',
      'waving': 'dance',
      'arms_crossed': 'idle',
      'shaking_head': 'walk',
      'crawling_in': 'walk',
      'thumbs_up': 'dance',
      'clapping': 'dance',
      'facepalm': 'idle',
      'beckoning': 'walk',
    },
  );

  static const owl = CharacterConfig(
    id: 'owl',
    displayName: 'Owl',
    atlasAsset: 'assets/spine/owl/owl-pma.atlas',
    skelAsset: 'assets/spine/owl/owl-pro.skel',
    supportsLipSync: false,
    oneShotAnimations: {'blink'},
    idleAnimation: 'idle',
    emotionAnimations: {
      'neutral': 'idle',
      'happy': 'up',
      'angry': 'down',
      'sad': 'down',
      'surprised': 'up',
      'annoyed': 'left',
      'disappointed': 'down',
      'scolding': 'right',
      'proud': 'up',
      'worried': 'left',
    },
    gestureAnimations: {
      'idle': 'idle',
      'pointing': 'right',
      'waving': 'up',
      'arms_crossed': 'down',
      'shaking_head': 'left',
      'crawling_in': 'up',
      'thumbs_up': 'up',
      'clapping': 'up',
      'facepalm': 'down',
      'beckoning': 'right',
    },
  );
}
